apiVersion: apps/v1
kind: ReplicaSet
metadata:
     name: myngpod
spec:
  replicas: 2
  selector:
    matchLabels:
       app: development
  template:
    metadata:
       labels:
         app: development
    spec:
     containers:
           - image: nginx
             name: ngcontainer
             ports:
              - name: http
                containerPort: 80
              - name: https
                containerPort: 443